- hosts: all
  vars_files:
    - group_vars/all.yml
  tasks:

    - name: Container include - Upgraders
      tags: container-upgrader
      include_tasks:  containers/dockerContainer.yml
      vars:
         containers:
              UpgradeO:
                 name: Upgrader-Ocata
                 target: all
                 image: "ocata"
                 command: "/bin/sleep infinity"
                 networks:
                   - name: bridge
                 mappings:
                   templates:
                     cinder.conf:
                         src: cinder.conf.j2
                         dest: /etc/cinder/cinder.conf
                         generic:
                     nova.conf:
                        src: nova.conf.j2
                        dest: /etc/nova/nova.conf
                        generic:

              UpgradeQ:
                 name: Upgrader-Queens
                 target: all
                 image: "queens"
                 command: "/bin/sleep infinity"
                 networks:
                   - name: bridge
                 mappings:
                   templates:
                     cinder.conf:
                         src: cinder.conf.j2
                         dest: /etc/cinder/cinder.conf
                         generic:
                     nova.conf:
                        src: nova.conf.j2
                        dest: /etc/nova/nova.conf
                        generic:

              UpgradeS:
                 name: Upgrader-Stein
                 target: all
                 image: "stein"
                 command: "/bin/sleep infinity"
                 networks:
                   - name: bridge
                 mappings:
                   templates:
                     cinder.conf:
                         src: cinder.conf.j2
                         dest: /etc/cinder/cinder.conf
                         generic:
                     nova.conf:
                        src: nova.conf.j2
                        dest: /etc/nova/nova.conf
                        generic:

              UpgradeU:
                 name: Upgrader-Ussuri
                 target: all
                 image: "ussuri"
                 command: "/bin/sleep infinity"
                 networks:
                   - name: bridge
                 mappings:
                   templates:
                     cinder.conf:
                         src: cinder.conf.j2
                         dest: /etc/cinder/cinder.conf
                         generic:
                     nova.conf:
                        src: nova.conf.j2
                        dest: /etc/nova/nova.conf
                        generic:

              KeystoneV:
                name: Keystone-Upgrader-Victoria
                target: all
                image: "victoria"
                command: "/bin/sleep infinity"
                networks:
                  - name: bridge
                mappings:
                  templates:
                    keystone.conf:
                        src: keystone.conf.j2
                        dest: /etc/keystone/keystone.conf
                        generic:

              NovaV:
                name: Nova-Upgrader-Victoria
                target: all
                image: "victoria"
                command: "/bin/sleep infinity"
                networks:
                  - name: bridge
                mappings:
                  templates:
                    nova.conf:
                        src: nova.conf.j2
                        dest: /etc/nova/nova.conf
                        generic:

              GlanceV:
                name: Glance-Upgrader-Victoria
                target: all
                image: "victoria"
                command: "/bin/sleep infinity"
                networks:
                    - name: bridge
                mappings:
                    templates:
                      glance.conf:
                        src: glance-api.conf.j2
                        dest: /etc/glance/glance-api.conf
                        generic:

              NeutronV:
                name: Neutron-Upgrader-Victoria
                target: all
                image: "victoria"
                command: "/bin/sleep infinity"
                networks:
                  - name: bridge
                mappings:
                  templates:
                    neutron.conf:
                        src: neutron.conf.j2
                        dest: /etc/neutron/neutron.conf
                        generic:
                    ml2:
                        src: ml2_conf.ini.j2
                        dest: /etc/neutron/plugins/ml2/ml2_conf.ini
                        generic:

              CinderV:
                 name: Upgrader-Victoria
                 target: all
                 image: "victoria"
                 command: "/bin/sleep infinity"
                 networks:
                   - name: bridge
                 mappings:
                   templates:
                     cinder.conf:
                         src: cinder.conf.j2
                         dest: /etc/cinder/cinder.conf
                         generic:


      with_dict: "{{containers}}"
      when: item.value.target in group_names

  become: yes
  become_user: root
